# SPDX-License-Identifier: MIT OR Apache-2.0
# bankml 0.3.2 builds with Rust 1.99: the C API (capi/) defines a C-variadic function, stabilized in 1.99.
# Pinned here, not as the machine default; rustup installs it on first use.
[toolchain]
channel = "1.99.0"
components = ["clippy"]
